### PR TITLE
fails with dotnet version 7.x.x

### LINKED ISSUE #24: Action fails with dotnet version 7.x.x
When using `actions/setup-dotnet` with version `7.x.x`, the job consistently fails with the error message:
```
Can't find suitable dotnet or node installation to install retype package with.
```

Workflow file:
```
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Build doc site
        uses: retypeapp/action-build@latest
        with:
          license: ${{ secrets.RETYPE_LICENSE_KEY }}
```

I believe this line https://github.com/retypeapp/action-build/blob/main/build.sh#L28 is only checking for dotnet --version == 5 which is causing this issue. I tried to use setup-dotnet with dotnet-version: 5.x.x as a workaround, but this didn't work for retype version 3.0.3 as it required atleast dotnet v 7.

### PR DESCRIPTION
**Pull request by geoffreymcgill**
Closes https://github.com/objectdotnet/retype-app/issues/1648

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -25,10 +25,10 @@ fi
 echo "Working directory is: $(pwd)"
 
 # We prefer dotnet if available as the package size is (much) smaller.
-if which dotnet > /dev/null 2>&1 && [ "$(dotnet --version | cut -f1 -d.)" == "5" ]; then
+if which dotnet > /dev/null 2>&1 && [ "$(dotnet --version | cut -f1 -d.)" -ge 5 ]; then
```
Comment (fabriciomurta) [inline build.sh:28]: This is good enough for compatibility and future proof.

Ideally, it should match the installed/chosen .NET version if setup-dotnet step is run... But I can't think of a reliable way to check that without adding extra clobber for the end user; so `-ge 5` should be good enough. Perhaps limit to the supported version numbers (check `-ge 5` **and** `-le 7`). But then there should be a reliable way to update this check every time .NET version support is upgraded.

**Review by fabriciomurta — APPROVED** [review]
This should be good enough to ensure the `dotnet` CLI is chosen (instead of `npm`) whenever a valid one is installed; although it could potentially trigger an error, say, if .NET 8 is released and set by `setup-dotnet` and the action attempts to install a `retype` that only works with .NET 7 using the `dotnet` CLI. We should keep an eye open for that scenario in the future.
